//this file is generated by codedump tool at 1/16/2019 13:09:24 do NOT edit it !

#ifndef __AnniversaryCampaign__PARSER_H__
#define __AnniversaryCampaign__PARSER_H__
#include <map>
#include <vector>
#include <string>
#include <platform/platform_shared/dynamic_config.h>



struct RewardInfo
{
     type; 
     boy_id; 
     girl_id; 
     num; 
};


struct SeatNeed
{
    RewardInfo need; 
};


struct AnnyMisc
{
     campaign_id; 
     carnival_activity; 
};


struct SeatMisc
{
     seat_a_id; 
     seat_b_id; 
     seat_c_id; 
};


struct SeatUpgrade
{
     seat_id; 
     next_seat_id; 
    SeatNeed need; 
};


struct Seat
{
    SeatMisc misc; 
     upgrade; 
};


struct Day
{
     dayid; 
    RewardInfo reward; 
};


struct AnniversaryConfig
{
    AnnyMisc misc; 
    Seat seat; 
     signin_cfg; 
};


class AnniversaryCampaignParser: public CDynamicConfig
{
public:
    bool Init(const char* xmlfile);
    virtual bool LoadConfig(variant* root);
    const AnniversaryConfig& GetConfig(){return m_config;}
private:
    bool ParseRewardInfo(variant* root, RewardInfo& info);
    bool ParseSeatNeed(variant* root, SeatNeed& info);
    bool ParseAnnyMisc(variant* root, AnnyMisc& info);
    bool ParseSeatMisc(variant* root, SeatMisc& info);
    bool ParseSeatUpgrade(variant* root, SeatUpgrade& info);
    bool ParseSeat(variant* root, Seat& info);
    bool ParseDay(variant* root, Day& info);
    bool ParseAnniversaryConfig(variant* root, AnniversaryConfig& info);
private:
    AnniversaryConfig m_config;
};

#endif //__AnniversaryCampaign__PARSER_H__
