using common;

class lockui{
    float locktime;
}


class maskinfo{
    int winShowType;
    Pos maskPos;
    Size masksize;
    string anchorType;
    int rotz;
    [optional]
    bool isMaskTransparent;
    Pos windowpos;
}

class action{
    int type;
    [optional]
    string param1;
    [optional]
    int npc;
    [optional]
    float delay;
}

class condition{
    int type;
    [optional]
    string param1;
}
class Step{
    int id;
    int type;
    int backto;
    [optional]
    Pos pos;
    [optional]
    bool isLocalStep;
    [optional]
    string padView;
    [optional]
    lockui lockuiv;
    [optional]
    maskinfo maskinfov;
    [optional]
    List<string> pop_tip_list;
    [optional]
    List<action> comm_actions;
    [optional]
    List<condition> finish_conditions;
    [optional]
    List<condition> trigger_conditions;
}

class Group{
    [key]
    int groupid;
    int guidetype;
    List<Step> steps;
}

class flower{
    int id;
    int num;
    int type;
}

class item{
    int type_id;
    [string]
    Pos pos;
    [string]
    Pos xiaoyao_pos;
}

class res{
    string picture;
}

class other_guide_config{
    int garden_guide_seed_id;
    int garden_per_seed_harvest_num;
    int garden_synthetic_flower_per_need;
    List<flower> garden_synthetic_flower_list;
    List<item> collection_position_config;
    int forge_product_id_boy;
    int forge_product_id_girl;
    string happy_match_title_res;
    List<res> happy_match_res;
    string arena2v2_match_title_res;
    List<res> arena2v2_match_res;
}

[root]
class Groups{
    Dict<int,Group> groups;
    other_guide_config other_guide_config;
}