class XmlMusicInfoMode{
    int value;
}

class XmlMusic{
    [key]
    int id;
    string name;
    string singer_name;
    int bpm;
    int duration;
    int ogg_id;
    int star;
    List<XmlMusicInfoMode> XmlMusicInfoModeList;
}

class XmlMusicDifficulty{
    int diff;
    int max_star;
}

[root]
class XmlMusicInfo{
    Dict<int,XmlMusic> XmlMusicList;
    List<XmlMusicDifficulty> XmlMusicDifficultyList;
}