//this file is generated by codedump tool at ${META_DATETIME} do NOT edit it !

#ifndef __${META_NAME}__PARSER_H__
#define __${META_NAME}__PARSER_H__
#include <map>
#include <vector>
#include <string>
#include <platform/platform_shared/dynamic_config.h>

@{BEGIN_ENUM}
${ENUM_COMMENT}
enum ${ENUM_NAME}
{
@{BEGIN_ENUM_FIELD}
    ${ENUM_FIELD_NAME} = ${ENUM_FIELD_VALUE}, ${ENUM_FIELD_COMMENT}
@{END_ENUM_FIELD}
};

@{END_ENUM}

@{BEGIN_CLASS}
${CLASS_COMMENT}
struct ${CLASS_NAME}
{
@{BEGIN_CLASS_FIELD}
    ${CLASS_FIELD_TYPE} ${CLASS_FIELD_NAME}; ${CLASS_FIELD_COMMENT}
@{END_CLASS_FIELD}
};

@{END_CLASS}

class ${META_NAME}Parser: public CDynamicConfig
{
public:
    bool Init(const char* xmlfile);
    virtual bool LoadConfig(variant* root);
    const ${META_ROOT_CLASS_NAME}& GetConfig(){return m_config;}
private:
@{BEGIN_CLASS}
    bool Parse${CLASS_NAME}(variant* root, ${CLASS_NAME}& info);
@{END_CLASS}
private:
    ${META_ROOT_CLASS_NAME} m_config;
};

#endif //__${META_NAME}__PARSER_H__