//this file is generated by xml2code tool 7/18/2018 19:28:28
//DO NOT EDIT IT !

using System;
using System.Collections.Generic;
using System.IO;
using System.Xml;
using GYGeneric;

namespace GYXMLData
{

    
    public class check :IXmlParser
    {
        public  formal_is_check_env = false; 
        public  check_is_check_env = false; 
        public  is_show_wx_gift_center = false; 
        public  is_block_func_in_gray_server = false; 

        public bool Parse(XmlNode node)
        {
            if(node.Attributes!=null && node.Attributes["formal_is_check_env"]!=null)
            {
                formal_is_check_env = bool.Parse(node.Attributes["formal_is_check_env"].Value);
            }
            else
            {
                var child = node.SelectSingleNode("formal_is_check_env");
                if(child!=null)
                {
                    formal_is_check_env = bool.Parse(child.InnerText);
                }
            }
            if(node.Attributes!=null && node.Attributes["check_is_check_env"]!=null)
            {
                check_is_check_env = bool.Parse(node.Attributes["check_is_check_env"].Value);
            }
            else
            {
                var child = node.SelectSingleNode("check_is_check_env");
                if(child!=null)
                {
                    check_is_check_env = bool.Parse(child.InnerText);
                }
            }
            if(node.Attributes!=null && node.Attributes["is_show_wx_gift_center"]!=null)
            {
                is_show_wx_gift_center = bool.Parse(node.Attributes["is_show_wx_gift_center"].Value);
            }
            else
            {
                var child = node.SelectSingleNode("is_show_wx_gift_center");
                if(child!=null)
                {
                    is_show_wx_gift_center = bool.Parse(child.InnerText);
                }
            }
            if(node.Attributes!=null && node.Attributes["is_block_func_in_gray_server"]!=null)
            {
                is_block_func_in_gray_server = bool.Parse(node.Attributes["is_block_func_in_gray_server"].Value);
            }
            else
            {
                var child = node.SelectSingleNode("is_block_func_in_gray_server");
                if(child!=null)
                {
                    is_block_func_in_gray_server = bool.Parse(child.InnerText);
                }
            }

            return true;
        }
    }

}
