//this file is generated by xml2code tool at 7/19/2018 17:04:32
//do NOT edit it !

#pragma once
#include <map>
#include <vector>
#include <string>
#include "../shared/xml_config_interface.h"

//enum

//class

struct check : public IXmlParser
{
    bool formal_is_check_env; 
    bool check_is_check_env; 
    bool is_show_wx_gift_center; 
    bool is_block_func_in_gray_server; 
    bool LoadFromString(std::string s);
    bool LoadFromVariant(variant* v);
};

//hotfix
class check_hotfix_xml:public IHotfixXml
{
public:
    virtual bool Load(variant* v);
    virtual void* Root(){return root;}
private:
    check* root;
};
