//this file is generated by xml2code tool at 7/19/2018 17:04:32
//do NOT edit it !

#include "check.h"
#include <sstream>

bool check::LoadFromString(std::string s)
{
    return false;
}

bool check::LoadFromVariant(variant* v)
{
    if(from_str_variant(v->get_child("formal_is_check_env"), formal_is_check_env)<0) return false;
    if(from_str_variant(v->get_child("check_is_check_env"), check_is_check_env)<0) return false;
    if(from_str_variant(v->get_child("is_show_wx_gift_center"), is_show_wx_gift_center)<0) return false;
    if(from_str_variant(v->get_child("is_block_func_in_gray_server"), is_block_func_in_gray_server)<0) return false;

    return true;
}

