//this file is generated by xml2code tool at 7/19/2018 17:04:32
//do NOT edit it !

#pragma once
#include <map>
#include <vector>
#include <string>
#include "../shared/xml_config_interface.h"

//enum

//class
//消耗物品的配置格式
struct CostItem : public IXmlParser
{
    int type; 
    int id; 
    int count; 
    bool LoadFromString(std::string s);
    bool LoadFromVariant(variant* v);
};
//奖励
struct Reward : public IXmlParser
{
    int type; 
    int id; 
    int count; 
    bool LoadFromString(std::string s);
    bool LoadFromVariant(variant* v);
};
//场景对象布局结构
struct ObjectLayout : public IXmlParser
{
    int id; 
    int x; 
    int y; 
    int angle; 
    bool LoadFromString(std::string s);
    bool LoadFromVariant(variant* v);
};

struct bodyPart : public IXmlParser
{
    int type; 
    int src; 
    bool LoadFromString(std::string s);
    bool LoadFromVariant(variant* v);
};

struct Pos : public IXmlParser
{
    int x; 
    int y; 
    bool LoadFromString(std::string s);
    bool LoadFromVariant(variant* v);
};

struct Size : public IXmlParser
{
    int w; 
    int h; 
    bool LoadFromString(std::string s);
    bool LoadFromVariant(variant* v);
};
