//this file is generated by xml2code tool 7/18/2018 19:28:28
//DO NOT EDIT IT !

using System;
using System.Collections.Generic;
using System.Xml;

namespace GYXMLData
{

    public class CostItem 
    {
        public int type = 0; 
        public int id = 0; 
        public int count = 0; 
    }
    public class Reward 
    {
        public int type = 0; 
        public int id = 0; 
        public int count = 0; 
    }
    public class ObjectLayout 
    {
        public int id = 0; 
        public int x = 0; 
        public int y = 0; 
        public int angle = 0; 
    }
    public class bodyPart 
    {
        public int type = ; 
        public int src = ; 
    }
    public class Pos 
    {
        public int x = ; 
        public int y = ; 
    }
    public class Size 
    {
        public int w = ; 
        public int h = ; 
    }
}
