//this file is generated by xml2code tool at 7/19/2018 17:04:32
//do NOT edit it !

#pragma once
#include <map>
#include <vector>
#include <string>
#include "../shared/xml_config_interface.h"

//enum

//class

struct Answer : public IXmlParser
{
    int id; 
    std::string content; 
    int result; 
    std::vector<std::string> choice_answer_list; 
    bool LoadFromString(std::string s);
    bool LoadFromVariant(variant* v);
};

struct AnswerLibrary : public IXmlParser
{
    std::map<int,Answer> answers; 
    bool LoadFromString(std::string s);
    bool LoadFromVariant(variant* v);
};

//hotfix
class community_answer_library_hotfix_xml:public IHotfixXml
{
public:
    virtual bool Load(variant* v);
    virtual void* Root(){return root;}
private:
    AnswerLibrary* root;
};
