//this file is generated by xml2code tool at 7/19/2018 17:04:32
//do NOT edit it !

#pragma once
#include <map>
#include <vector>
#include <string>
#include "../shared/xml_config_interface.h"
#include "common.h"

//enum

//class

struct Dress : public IXmlParser
{
    int id; 
    std::string name; 
    int gender; 
    int type; 
    int sub_type; 
    bool can_overlay; 
    bool show_inbag; 
    std::vector<bodyPart> bodyPartList; 
    bool LoadFromString(std::string s);
    bool LoadFromVariant(variant* v);
};

struct DressListInfo : public IXmlParser
{
    std::map<int,Dress> DressList; 
    bool LoadFromString(std::string s);
    bool LoadFromVariant(variant* v);
};

//hotfix
class dress_hotfix_xml:public IHotfixXml
{
public:
    virtual bool Load(variant* v);
    virtual void* Root(){return root;}
private:
    DressListInfo* root;
};
