//this file is generated by xml2code tool at 7/19/2018 17:04:32
//do NOT edit it !

#include "dress.h"
#include <sstream>

bool Dress::LoadFromString(std::string s)
{
    return false;
}
bool DressListInfo::LoadFromString(std::string s)
{
    return false;
}

bool Dress::LoadFromVariant(variant* v)
{
    {
        variant* v_list = v->get_child("bodyPartList");
        if(v_list == NULL)
        {
            v_list = v;
        }
        int n = v_list->get_child_count();
        for(int i=0; i<n; i++)
        {
            if(!strcmp(v_list->get_key(i), "bodyPart"))
            {
                bodyPart element;
                variant* v_element = v_list->get_child(i);
                if(!element.LoadFromVariant(v_element))
                {
                    return false;
                }
                bodyPartList.emplace_back(element);
            }
        }
    }
    if(from_str_variant(v->get_child("name"), name)<0) return false;
    if(from_str_variant(v->get_child("id"), id)<0) return false;
    if(from_str_variant(v->get_child("gender"), gender)<0) return false;
    if(from_str_variant(v->get_child("type"), type)<0) return false;
    if(from_str_variant(v->get_child("sub_type"), sub_type)<0) return false;
    if(from_str_variant(v->get_child("can_overlay"), can_overlay)<0) return false;
    if(from_str_variant(v->get_child("show_inbag"), show_inbag)<0) return false;

    return true;
}
bool DressListInfo::LoadFromVariant(variant* v)
{
    {
        variant* v_dict = v->get_child("DressList");
        if(v_dict == NULL)
        {
            v_dict = v;
        }
        int n = v_dict->get_child_count();
        for(int i=0; i<n; i++)
        {
            if(!strcmp(v_dict->get_key(i), "Dress"))
            {
                Dress element;
                variant* v_element = v_dict->get_child(i);
                if(!element.LoadFromVariant(v_element))
                {
                    return false;
                }
                DressList.emplace(element.id, element);
            }
        }
    }

    return true;
}

