//this file is generated by xml2code tool at 7/19/2018 17:04:32
//do NOT edit it !

#pragma once
#include <map>
#include <vector>
#include <string>
#include "../shared/xml_config_interface.h"
#include "common.h"

//enum

//class

struct section : public IXmlParser
{
    int id; 
    std::string name; 
    int chapterId; 
    int sceneId; 
    int default_env_id; 
    Pos position; 
    int section_type; 
    int unlocklevel; 
    int difficulty; 
    int music_id; 
    int plot_id; 
    int pre_plot_id; 
    int latter_plot_id; 
    std::vector<int> pre_sectionId; 
    std::string describe; 
    std::string force_main; 
    std::string invisible1; 
    std::string invisible2; 
    std::string buff; 
    std::string normal_rewards; 
    std::string first_rewards; 
    bool LoadFromString(std::string s);
    bool LoadFromVariant(variant* v);
};

struct SectionList : public IXmlParser
{
    std::map<int,section> section_list; 
    bool LoadFromString(std::string s);
    bool LoadFromVariant(variant* v);
};

//hotfix
class section_hotfix_xml:public IHotfixXml
{
public:
    virtual bool Load(variant* v);
    virtual void* Root(){return root;}
private:
    SectionList* root;
};
