// this file is generated by xml2code tool ${DATETIME}
// DO NOT EDIT IT

#pragma once

#include "accouterment.h"
#include "cardrole.h"
#include "check.h"
#include "community_answer_library.h"
#include "dress.h"
#include "guide.h"
#include "home_config.h"
#include "music_info.h"
#include "section.h"
#include "simulation_table.h"
