//this file is generated by codedump ${DATETIME}
//DO NOT EDIT IT !

using System;
using System.Text;
using System.Collections.Generic;
using System.IO;
using System.Xml;

namespace GYXMLData
{
    @{BEGIN_META_IF(EQ,${META_HAS_ROOT},true)}
    public class ${ROOT_CLASS_NAME}XmlParser:XMLParserBase
    {
        public override Type GetXmlDataType()
        {
            return typeof(${ROOT_CLASS_NAME}XmlData);
        }
        public override object ParserXML(XmlNode node, byte[] bytes)
        {
            ${ROOT_CLASS_NAME}XmlData data = new ${ROOT_CLASS_NAME}XmlData();
            if(!data.Parse(node))
            {
                throw new Exception("Parse xml error: ${META_NAME}");
                //return null;
            }
            return data;
        }
    }
    @{END_META_IF}
}