//this file is generated by codedump tool at ${G.DATETIME} do NOT edit it !
#pragma once

#include <map>
#include <vector>
#include <string>
#include <platform/platform_shared/bulk_reader.h>

@{FOREACH(Enum IN ${Meta.EnumList})}
${Enum.Comment}
enum ${Enum.Name}
{
@{FOREACH(Field IN ${Enum.FieldList})}
    ${Field.Name} = ${Field.Value}, ${Field.Comment}
@{END_FOREACH}
};

@{END_FOREACH}

@{FOREACH(Class IN ${Meta.ClassList})}
${Class.Comment}
struct ${Class.Name}
{
@{FOREACH(Field IN ${Class.FieldList})}
    ${Field.Type} ${Field.Name}; ${Field.Comment}
@{END_FOREACH}
};

@{END_FOREACH}

class ${Meta.Name}Parser : public ConfReader<${Meta.Name}Parser>
{
public:
    bool Initialize(const char* file);
    virtual bool LoadConfig(nlohmann::json& root, bool init);
    const ${Meta.RootClassName}& GetConfig(){return m_config;}
private:
@{FOREACH(Class IN ${Meta.ClassList})}
    bool Parse${Class.Name}(nlohmann::json& root, ${Class.Name}& info);
@{END_FOREACH}
private:
    ${Meta.RootClassName} m_config;
};

