//this file is generated by codedump tool at ${G.DATETIME} do NOT edit it !

#ifndef __${Meta.Name}__PARSER_H__
#define __${Meta.Name}__PARSER_H__
#include <map>
#include <vector>
#include <string>
#include <platform/platform_shared/dynamic_config.h>

@{FOREACH(Enum IN ${Meta.EnumList})}
${Enum.Comment}
enum ${Enum.Name}
{
@{FOREACH(Field IN ${Enum.FieldList})}
    ${Field.Name} = ${Field.Value}, ${Field.Comment}
@{END_FOREACH}
};

@{END_FOREACH}

@{FOREACH(Class IN ${Meta.ClassList})}
${Class.Comment}
struct ${Class.Name}
{
@{FOREACH(Field IN ${Class.FieldList})}
    ${Field.Type} ${Field.Name}; ${Field.Comment}
@{END_FOREACH}
};

@{END_FOREACH}

class ${Meta.Name}Parser: public CDynamicConfig
{
public:
    bool Init(const char* xmlfile);
    virtual bool LoadConfig(variant* root);
    const ${Meta.RootClassName}& GetConfig(){return m_config;}
private:
@{FOREACH(Class IN ${Meta.ClassList})}
    bool Parse${Class.Name}(variant* root, ${Class.Name}& info);
@{END_FOREACH}
private:
    ${Meta.RootClassName} m_config;
};

#endif //__${Meta.Name}__PARSER_H__