
set ProjectName = Project_Skill;


class skill_data_info
{
	[pstflags(field,autoinc)]
	int dbid;
	[pstflags(field,primary)]
	TPersistID ownerid;
	[pstflags(field)]
	int skillid;
	string name;
	string desc;
	[pstflags(field)]
	int level;
	[pstflags(field,datetime)]
	time_t create_time;
}

